<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UmlMM">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownerScope"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Classifier" eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelelement" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribut" eSuperTypes="#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" upperBound="-1"
        eType="#//Classifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classe" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" eSuperTypes="#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//Namespace"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//Model"/>
</ecore:EPackage>
